title: jekyll-bootstrap
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
copyrights: Copyrights 2017 - Your awesome company
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: oleingemann
github_username:  jekyll
facebook_username: jekyll-rb
facebook_link: /skolehuset
permalink: pretty
#permalink: /:categories/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
blog:
  title: Blog title
  url: /blog
documentation:
  title: Documentation title
  url: /documentation
collections:
  docs:
    general:
      output: true
    guide:
      output: true
sass:
    sass_dir: _sass

lang:
    latest-posts: Latest
    sign-up-to-our-newsletter: Get it fresh!
    email: Your email
    docs-footer-message: Suggestions on how this page could be better?
    docs-footer-message-contact-message: Let us know!
    docs-footer-message-contact-email: post@jekyll.com
    read-more: Read more...
    documentation: Documentation
    blog: Blog
    related-posts: related posts
    welcome-to-docs: Welcome to the documentation central.

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
